spark.jars.packages              org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.5.2,org.apache.hadoop:hadoop-aws:3.3.4
spark.sql.extensions             org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.my_catalog     org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.my_catalog.type rest
spark.sql.catalog.my_catalog.uri  http://rest-catalog:8181
spark.sql.catalog.my_catalog.io-impl org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.my_catalog.warehouse s3a://lakehouse/warehouse/
spark.sql.catalog.my_catalog.s3.endpoint http://minio:9000
spark.sql.catalog.my_catalog.s3.path-style-access true
spark.sql.catalog.my_catalog.s3.region              us-east-1
spark.sql.catalog.my_catalog.client.region          us-east-1